
name: Merge_Main
on: 
  push:
jobs:
  raise-pullrequest:
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - run: gh pr create

  merge-pullrequest:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - run: gh pr merge PULL-REQUEST


