
name: Merge_Main
on: 
  push:
jobs:
  raise-pullrequest:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create -f ${{ github.ref }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-pullrequest:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge PULL-REQUEST
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


